import "./globals.css";
import { Toaster } from "react-hot-toast";
import AuthProvider from "@/contexts/AuthContext";

export const metadata = {
  title: "Ecommerce App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-gray-900 min-h-screen`}>
        <AuthProvider>
          {children}
          <Toaster position="bottom-center" reverseOrder={false} />
        </AuthProvider>
      </body>
    </html>
  );
}
